---
- name: "Use Tags"
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: "Tache non executée"
      debug:
        msg: "Non tagé"

    - name: "Tache executée"
      tags: "OK"
      debug:
        msg: "Tagé"

# Utilisation :
# ansible-playbook -i Inventory.txt PB-Tag.yml --tags "OK"
# ansible-playbook -i Inventory.txt PB-Tag.yml --skip "OK"
