---
- name: "Use Tags"
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: "Tache non executée"
      debug:
        msg: "Non tagé"

    - name: "Tache executée"
      tags: "OK"
      debug:
        msg: "Tagé"
